import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                // Node.js globals
                process: 'readonly',
                console: 'readonly',
                Buffer: 'readonly',
                globalThis: 'readonly',
                // Browser globals (for frontend JS files)
                window: 'readonly',
                document: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                fetch: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                HTMLElement: 'readonly',
                AbortController: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
                performance: 'readonly',
                THREE: 'readonly',
                tailwind: 'readonly',
                matchMedia: 'readonly',
                ResizeObserver: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                getComputedStyle: 'readonly',
                Audio: 'readonly',
                Image: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                MouseEvent: 'readonly',
                KeyboardEvent: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                location: 'readonly',
                history: 'readonly',
                crypto: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-console': 'off',
            'no-constant-condition': 'warn',
        },
    },
    {
        ignores: ['node_modules/', 'dist/', 'test-results/', '*.config.js', 'tests/**', 'scripts/**'],
    },
];
